variables:
  TEST_SERVER: 192.168.1.204
  TEST_HOST_DIR: /var/file/workspace-web/
  TEST_SOURCE_FOLDER: ./dist/

  PROD_SERVER: 192.168.1.231
  PROD_HOST_DIR: /var/workspace-web/
  PROD_SOURCE_FOLDER: ./dist/
  TAG_VERSION: 1.0.0
test-deploy:
  before_script:
    - mkdir -p ~/.ssh/
    - cp $DEPLOY_PRIVATE_KEY ~/.ssh/id_rsa && chmod 700 ~/.ssh/id_rsa
    - cp $KNOWN_HOSTS ~/.ssh/known_hosts
    - git config core.longpaths true
    - echo "$CI_COMMIT_REF_NAME"
    - npm config set registry https://registry.npmmirror.com
    - npm install -g pnpm
    - pnpm install --no-frozen-lockfile
    - echo "build begin!"
  script:
    - pnpm build
  after_script:
    - echo "build success!"
    - sshpass -p $TEST_USER_PASSWORD scp -o StrictHostKeyChecking=no -r $TEST_SOURCE_FOLDER/** workspace@$TEST_SERVER:$TEST_HOST_DIR 
    - echo "deploy success!"    
  rules:
    - if: $DEPLOY =~ /^test/
  tags:
    - pnpm
prod-deploy:
  before_script:
    - mkdir -p ~/.ssh/
    - cp $DEPLOY_PRIVATE_KEY ~/.ssh/id_rsa && chmod 700 ~/.ssh/id_rsa
    - cp $KNOWN_HOSTS ~/.ssh/known_hosts
    - git config core.longpaths true
    - git config --global user.email "erpmsg@deogra.com"
    - git config --global user.name "Administrator"
    - git remote set-url origin git@192.168.1.235:webui/workspace.web.git
    - git checkout -B "$CI_COMMIT_REF_NAME"
    - npm config set registry https://registry.npmmirror.com/
    - npm install -g pnpm
    - pnpm install --no-frozen-lockfile
  script:
    - sh chgVer.sh
    - git commit ./package.json -m "修改版本号"
    - TAG_VERSION=`sed -n '/version/p' ./package.json | sed 's/"/\n/g' | sed '1,3d' | sed '2,3d'`
    - git tag -a "workspace.web.$TAG_VERSION" -m "$TAG_VERSION"
    - git push origin "$CI_COMMIT_REF_NAME":dev --follow-tags
    - pnpm build
    - ls -l
  after_script:
    - sshpass -p "$PROD_USER_PASSWORD" scp -o StrictHostKeyChecking=no -r $PROD_SOURCE_FOLDER/** workspace@$PROD_SERVER:$PROD_HOST_DIR
  allow_failure: false
  rules:
    - if: $DEPLOY =~ /^prod/
  tags:
    - pnpm
