import { ref } from "vue";

export const useTableList = () => {
  const appearanceList = ref([
    {
      distinguish: "2.外观",
      No: "2-1",
      testNum: 3,
      testItem: "外观",
      testReq: "",
      judgeStandard: "成形不良喷漆、色调不良、金属部生锈等",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "2.外观",
      No: "2-2",
      testNum: 2,
      testItem: "利边",
      testReq: "6N力施加在感知带（暂用卷烟纸代替），10个来回，移动5cm手感知",
      judgeStandard: "感知带割裂＜50%手没有刮手感",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "2.外观",
      No: "2-3",
      testNum: 1,
      testItem: "整机拆解结构和工艺示意",
      testReq: "拍照记录",
      judgeStandard: "拍照记录",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    }
  ]);

  const machineList = ref([
    {
      distinguish: "3.机械设计",
      No: "3-1",
      testNum: 3,
      testItem: "间隙、段差",
      testReq: "各部件的组合情况",
      judgeStandard: "间隙：≤0.5mm 段差：≤0.3mm",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-2",
      testNum: 3,
      testItem: "装配检查",
      testReq: "用手捏产品各部，操作产品各活动部件（如开关、手柄等），及晃动产品",
      judgeStandard: "操作顺畅，没有异响，,没有固定连接部件松动",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-3",
      testNum: 3,
      testItem: "配件连接强度（风嘴、柔风器等六个配件）",
      testReq: "配件安装到位用力晃动样机25次（正常使用中可能的最大力量）454g砝码作用于部件对接口的轴线，持续1min常温和高热高速工作10min后分别进行",
      judgeStandard: "外接配件不应出现松脱的现象",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-4",
      testNum: 3,
      testItem: "本体重量",
      testReq: "不包含包装材料的裸机重量",
      judgeStandard: "记录不含电源线和包含电源线的总重量",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-5",
      testNum: 3,
      testItem: "冷风按键强度",
      testReq: "5Kg.f力任意方向施压15秒",
      judgeStandard: "没有偏向与弯曲，功能正常",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "3.机械设计",
      No: "3-6",
      testNum: 1,
      testItem: "进气开口",
      testReq: "手持风筒的每个进气开口应配有屏蔽或类似物UL859：9.1.7项",
      judgeStandard: "开口不能大于0.004平方英寸(0.03平方厘米)",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "3.机械设计",
      No: "3-7",
      testNum: 3,
      testItem: "电源线长度",
      testReq: "UL 859：13.3.1.1项测量从线进入外壳，或线进入器具接线装置的末端，到线叶片的边缘或线进入附着插头的接地针最近点",
      judgeStandard: "1.52米-2.74米",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-8",
      testNum: 1,
      testItem: "电源线类型",
      testReq: "依据UL 859表13.2",
      judgeStandard:
        "符合UL 859表13.2的分类要求德龙常用线：20856，HPN, SPT-1, SPT-2, SVT,SJT, SJTW注：a SPT-1线，落地式器具不能使用，其它器具裸机重量不超过0.23Kg可以使用b HPN, SPT-2, SVT线，不能用于带有脚轮的落地器具",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-9",
      testNum: 3,
      testItem: "电源线拉力",
      testReq: "UL 859：48项断开电源线内部连接，施加35磅(156N)/1分钟注：手持式器具排除线的重量≤227克，施加拉力是20磅(89N)",
      judgeStandard: "再次施加拉力时，软线位移不应超过2mm软线没有损害能经受1250V 100mA 1min绝缘耐压测试电性能没有不良。",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-10",
      testNum: "",
      testItem: "电源线拉力",
      testReq: "CSA 22.2 No.36：7.12.1项施加88N/1分钟",
      judgeStandard: "软线没有损害能经受1000V 100mA 1min绝缘耐压测试电性能没有不良。",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-11",
      testNum: 1,
      testItem: "外壳强度实验",
      testReq:
        "UL 859：35.1项通过直径1/4英寸(6.4毫米)，长5英寸(127毫米)的圆钢杆平末端对外壳上的开口或保护口（进风网和出风网）施加5磅(22.2N)的力1分钟。圆杆是垂直的，相对于电器可置于任何位置",
      judgeStandard: "圆钢杆不可接触带电体爬电距离和电气间隔没有低于要求",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "3.机械设计",
      No: "3-12",
      testNum: 3,
      testItem: "本体使用跌落",
      testReq:
        "UL 859：46.4.4项CSA 22.2 No.36：7.13.3项额定电压（125V）操作至热稳定状态。仍然带电状态使器具自由下落从三英尺（约915mm）高跌落在硬木板上3次，每次器具都处于可能出现的不同位置。",
      judgeStandard: "功能操作正常电流和马达转速没有超过初始的±10%外壳和内部构造没有损坏没有带电部件外露没有火焰或熔融物喷出能经受1250V 100mA 1min绝缘耐压测试",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-13",
      testNum: 3,
      testItem: "本体存放跌落",
      testReq: "室温及不带电条件下从六英尺（约1829mm）高跌落在硬木板上3次。每次都是不同的面跌落在木板上。",
      judgeStandard: "再次通电没有火焰或熔融物喷出能经受1250V 100mA 1min绝缘耐压测试",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "3.机械设计",
      No: "3-14",
      testNum: 3,
      testItem: "风叶紧固",
      testReq: "风叶与马达轴间能承受8kgf.cm扭矩，并能承受10磅 1min的垂直吊重",
      judgeStandard: "不能转动 不能位移",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "3.机械设计",
      No: "3-15",
      testNum: "",
      testItem: "螺丝松退扭矩",
      testReq: "额定电压（125V）最大热量设置下操作至热稳定状态，然后冷却4小时后测量螺丝拧松力矩",
      judgeStandard: "外壳：***Kgf.cm±***Kgf.cm不能松退",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "3.机械设计",
      No: "3-16",
      testNum: 2,
      testItem: "螺丝紧固扭矩",
      testReq: "使用扭力计测量螺丝的紧固力矩",
      judgeStandard: "外壳：***Kgf.cm±***Kgf.cm无位移、滑头、螺钉及啮合螺纹无滑牙螺丝柱没有破裂和裂纹",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "3.机械设计",
      No: "3-17",
      testNum: 3,
      testItem: "发热丝端子拉力试验",
      testReq: "在最不利的方向施加于连接点5磅（2.27kg）的拉力，持续10秒",
      judgeStandard: "钟发热线在端子内不能有位移",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    }
  ]);

  const operationList = ref([
    {
      distinguish: "4.操作性",
      No: "4-1",
      testNum: 3,
      testItem: "冷风开关和档位开关操作",
      testReq: "操作按钮中心及不同方向的边缘",
      judgeStandard: "操作顺畅，没有异音，无接触不灵",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "4.操作性",
      No: "4-1",
      testNum: 3,
      testItem: "冷风开关和档位开关操作",
      testReq: "操作力",
      judgeStandard: "手感良好，10次取平均值***kg.f±***Kgf（参考）",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "4.操作性",
      No: "4-2",
      testNum: 3,
      testItem: "锁键力量测试",
      testReq: "推拉力计操作锁键解锁的力量各配件装入旋紧后，按压锁键至各配件方便取出",
      judgeStandard: "10次取平均值记录锁键解锁的力量",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "4.操作性",
      No: "4-3",
      testNum: 3,
      testItem: "电源线旋转性能",
      testReq: "电源软线松散自由垂落地面。产品转动轴线距地面1米，手握住产品向一个方向转动",
      judgeStandard: "a.电源软线与垂线的角度不能超过90°；\nb.没有卡住、异常音等；\nc.连接器转动时没有端子接触不良导致功能瞬间",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "4.操作性",
      No: "4-4",
      testNum: 3,
      testItem: "可拆卸部件安装（风嘴、柔风器等六个配件，进风网的拆卸和安装）",
      testReq: "部件安装和拆卸",
      judgeStandard: "操作方便不松动",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "4.操作性",
      No: "4-5",
      testNum: 3,
      testItem: "发梳头发抓力测试",
      testReq: "标准毛: W30mm*T1mm\n参照测试操作示意从发根匀速拉发至发梢，记录最大力",
      judgeStandard: "10次取平均值？？?N±？N",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const basePerformanceList = ref([
    {
      distinguish: "5.基本性能",
      No: "5-1",
      testNum: 5,
      testItem: "马达转速测试",
      testReq: "输入电源：125V 60Hz（设定档位开机后的电压）设定档位：高档；中档；低档；冷风 + 高/中/低档；",
      judgeStandard: "高档：？？？r.p.m中档：？？？r.p.m低档：？？？r.p.m冷风+高档：？？？r.p.m冷风+中档：？？？r.p.m冷风+低档：？？？r.p.m",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-2",
      testNum: 5,
      testItem: "噪音测试",
      testReq: "300mm的距离最严重方向（出风口方向除外）的噪音输入电源：125V 60Hz（设定档位开机后的电压）设定档位：高档；中档；低档；冷风 + 高/中/低档；",
      judgeStandard: "声音柔和，没有尖锐、刺耳或其它异常的声音≤82dBA（同时记录环境噪音）",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-3",
      testNum: 5,
      testItem: "风速测试",
      testReq: "在ID100×L1500mm内壁光滑的直管中测量出风口风速输入电源：125V 60Hz（设定档位开机后的电压）设定档位：冷风 + 高/中/低档；",
      judgeStandard: "测量治具出风口风速冷风+高档：＞6.5m/s冷风+中档：＞5.1m/s冷风+低档：＞5.7m/s",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-4",
      testNum: 5,
      testItem: "风量测试",
      testReq: "在ID100×L1500mm内壁光滑的直管中测量出风口风速输入电源：125V 60Hz（设定档位开机后的电压）设定档位：冷风 + 高/中/低档；",
      judgeStandard: "测量治具出风口速度不小于冷风+高档：？？？m³/分钟冷风+中档：？？？m³/分钟冷风+低档：？？？m³/分钟",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-5",
      testNum: 5,
      testItem: "发红检查",
      testReq: "输入电源：125V 60Hz（设定档位开机后的电压）设定档位：高档",
      judgeStandard: "正常室内照明（300-500LUX）条件下没有可见红光",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-6",
      testNum: 5,
      testItem: "震机检查",
      testReq: "输入电源：125V 60Hz（设定档位开机后的电压）设定档位：高档；中档；低档样机在各档位且无任何外力的情况下平放在光滑的玻璃面上行",
      judgeStandard: "在玻璃面上的移动距离小于5cm",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-7",
      testNum: 2,
      testItem: "风温测试(手持式吹风机）\n注：不可拆卸出风头的热气卷\n发钳和刷子不评估此项",
      testReq: "UL 859：44.5项记录53点温度，并计算最高5点的平均温度值（具体操作方法见右侧对象附件）",
      judgeStandard: "最大温升小于100K",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-7",
      testNum: 2,
      testItem: "风温测试(手持式吹风机）\n注：不可拆卸出风头的热气卷\n发钳和刷子不评估此项",
      testReq: "输入电源：125V 60Hz（设定档位开机后的电压）",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-7",
      testNum: 2,
      testItem: "风温测试(手持式吹风机）\n注：不可拆卸出风头的热气卷\n发钳和刷子不评估此项",
      testReq: "设定档位：高档",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-7",
      testNum: 2,
      testItem: "风温测试(手持式吹风机）\n注：不可拆卸出风头的热气卷\n发钳和刷子不评估此项",
      testReq: "风口没有附件和各个附件都在风口上",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-7",
      testNum: 2,
      testItem: "风温测试(手持式吹风机）\n注：不可拆卸出风头的热气卷\n发钳和刷子不评估此项",
      testReq: "评估最严厉的使用条件和支撑在最严厉的位置上（出风口垂直向上、向上45°、水平、向下45°、垂直向下）",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-8",
      testNum: 2,
      testItem: "早跳测试",
      testReq: "出风口带最小风口的风嘴距墙壁25.4mm开机运行15分钟。",
      judgeStandard: "操作过程中不能关机或不发热",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-8",
      testNum: 2,
      testItem: "早跳测试",
      testReq: "额定电压（125V）",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-8",
      testNum: 2,
      testItem: "早跳测试",
      testReq: "1.1倍额定电压（137.5V）",
      judgeStandard: "",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-9",
      testNum: 2,
      testItem: "停机跳测试",
      testReq: "出风口带最小风口的风嘴距墙壁25.4mm开机运行15分钟，然后关闭开关10秒再打开。",
      judgeStandard: "器具功能正常",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-9",
      testNum: 2,
      testItem: "停机跳测试",
      testReq: "额定电压（125V）",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-9",
      testNum: 2,
      testItem: "停机跳测试",
      testReq: "1.1倍额定电压（137.5V）",
      judgeStandard: "",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-10",
      testNum: 1,
      testItem: "功能操作和显示",
      testReq: "依据输入表",
      judgeStandard: "符合输入表要求",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-11",
      testNum: 2,
      testItem: "快速开关机",
      testReq: "额定电压3秒开，3秒关，操作50000次",
      judgeStandard: "没有故障发生",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "5.基本性能",
      No: "5-12",
      testNum: 2,
      testItem: "漏风检查",
      testReq: "额定电压，最大转速",
      judgeStandard: "器具外表面各装配缝隙没有风溢出",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "5.基本性能",
      No: "5-13",
      testNum: 2,
      testItem: "低温低压启动",
      testReq: "在-2±3℃放置4小时后立即在最低额定电压的0.85倍（106V）",
      judgeStandard: "工作状态正常",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "5.基本性能",
      No: "5-14",
      testNum: 2,
      testItem: "照明灯干扰试验",
      testReq: "白炽灯与试样并联在同一电路中，并在额定电压下设定各档位开机运行至稳定状态",
      judgeStandard: "白炽灯没有肉眼可见的闪烁状态",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const signList = ref([
    {
      distinguish: "1.标识",
      No: "1-1",
      testNum: 1,
      testItem: "插头标示",
      testReq: "认证标识、品牌、型号、产品额定电流和电压",
      judgeStandard: "依据规格书、认证证书",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-2",
      testNum: 1,
      testItem: "电源线标识",
      testReq: "认证标识、品牌、型号、铜芯线径",
      judgeStandard: "依据规格书、认证证书",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-3",
      testNum: 1,
      testItem: "电源线旋转尾图示",
      testReq: "拍照记录",
      judgeStandard: "拍照记录",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-4",
      testNum: 1,
      testItem: "安规电容标识",
      testReq: "认证标识、品牌、型号、产品额定电压、耐气候温度",
      judgeStandard: "依据规格书、认证证书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-5",
      testNum: 1,
      testItem: "温度保险丝标识",
      testReq: "认证标识、品牌、型号、Tf值温度",
      judgeStandard: "依据规格书、认证证书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-6",
      testNum: 1,
      testItem: "温控器标识",
      testReq: "认证标识、品牌、型号、动作温度",
      judgeStandard: "依据规格书、认证证书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-7",
      testNum: 1,
      testItem: "可控硅标识(T2)",
      testReq: "品牌、规格和型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-8",
      testNum: 1,
      testItem: "IC标识(U2)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-9",
      testNum: 1,
      testItem: "贴片IC(U1)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-10",
      testNum: 1,
      testItem: "MOS管(Q2)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-11",
      testNum: 1,
      testItem: "变压器(T1)",
      testReq: "品牌、型号、耐热等级",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-12",
      testNum: 1,
      testItem: "贴片二极管(D2)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-13",
      testNum: 1,
      testItem: "贴片二极管(D3)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-14",
      testNum: 1,
      testItem: "贴片整流桥(D1)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-15",
      testNum: 1,
      testItem: "贴片二极管(D4)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-16",
      testNum: 1,
      testItem: "贴片三极管(Q4)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-17",
      testNum: 1,
      testItem: "贴片三极管(Q1 Q3)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-18",
      testNum: 1,
      testItem: "贴片开关(SW1)",
      testReq: "品牌、型号",
      judgeStandard: "依据规格书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-19",
      testNum: 1,
      testItem: "马达标识",
      testReq: "品牌、型号、额定电压、额定功率、、耐热等级",
      judgeStandard: "依据规格书、认证证书",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-20",
      testNum: 1,
      testItem: "PCBA",
      testReq: "拍照记录",
      judgeStandard: "拍照记录",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "1.标识",
      No: "1-21",
      testNum: 1,
      testItem: "材料标识",
      testReq: "各部品的材料标示（25g以上）",
      judgeStandard: "与图纸一致",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    }
  ]);

  const electPerformanceList = ref([
    {
      distinguish: "6.电气性能",
      No: "6-1",
      testNum: 5,
      testItem: "功率",
      testReq: "UL 859：43项CSA 22.2 No.36：7.2项输入电源：125V 60Hz（设定档位开机后的电压）",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）中档：？？？W低档：？？？W冷风+高档：？？？W冷风+中档：？？？W冷风+低档：？？？W",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "6.电气性能",
      No: "6-1",
      testNum: 5,
      testItem: "功率",
      testReq: "档位：高档；中档；低档；冷风 + 高/中/低档；",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "6.电气性能",
      No: "6-2",
      testNum: 5,
      testItem: "电流",
      testReq: "设定档位：高档",
      judgeStandard: "不超温控器、温度保险丝、可控硅的额定电流",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "6.电气性能",
      No: "6-3",
      testNum: 2,
      testItem: "电源电压变动时的安全性",
      testReq: "UL 859：54.1项额定电压的120％（150V），工作最少50周期额定电压的75％（93V），工作最少15分钟",
      judgeStandard: "应没有绝缘击穿或机械破裂，或不适合的燃烧、凹痕、或接触片的焊接现象",
      judgeResult: "必须",
      dr1: true,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const badOperationList = ref([
    {
      distinguish: "7.异常操作",
      No: "7-1",
      testNum: 1,
      testItem: "限制进风测试",
      testReq: "UL 859：46.4.2项1.1倍额定功率，设定高热高速设置，风筒喷嘴水平放置注：软件有过流保护的需要取消保护设置",
      judgeStandard: "没有着火或喷火、火花、熔融金属或类似的现象任何部件没有崩塌或位移导致火灾或电击的危险",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-1",
      testNum: 1,
      testItem: "限制进风测试",
      testReq:
        "进气口每隔3分钟放一层棉质毛巾，直至所有电路的操作通过温度保险丝或温度控器的功能被中止，最多放10层，或棉质毛巾保持在进气口上操作7.5小时注1：可以用额外方法使棉质毛巾保持在其位置上（如胶带），但胶带不能堵塞气流",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-1",
      testNum: 1,
      testItem: "限制进风测试",
      testReq: "温控器短路，重复测试。温度保险丝熔断停止测试",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-2",
      testNum: 1,
      testItem: "限制出风测试",
      testReq: "UL 859：46.4.3项1.1倍额定功率，设定高热高速设置注：软件有过流保护的需要取消保护设置",
      judgeStandard: "没有着火或喷火、火花、熔融金属或类似的现象任何部件没有崩塌或位移导致火灾或电击的危险",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-2",
      testNum: 1,
      testItem: "限制出风测试",
      testReq:
        "耐温屏蔽胶纸（可使用金属片或其他抗燃烧原料）以50%、75%、90%、100%的出气孔面积被渐进地阻塞，四个位置的每一个阻塞3分钟。温度保险丝熔断停止测试，或100%的阻塞持续测试7.5小时",
      judgeStandard: "记录温度保险丝断开时和最高的温度",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-2",
      testNum: 1,
      testItem: "限制出风测试",
      testReq: "温控器短路，重复测试。温度保险丝熔断停止测试",
      judgeStandard: "记录温度保险丝断开时和最高的温度",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-3",
      testNum: 1,
      testItem: "马达减速测试",
      testReq: "UL 859：46.4.6项设定档位：高档注：软件有过流保护的需要取消保护设置",
      judgeStandard: "没有引起任何材料着火或喷火、火花、熔融金属或类似的结果绝缘耐压1250V 100mA 1分钟测试合格",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-3",
      testNum: 1,
      testItem: "马达减速测试",
      testReq: "记录器具额定输入电压（125V 60Hz）下马达的输入电压和功率，连同马达转速",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-3",
      testNum: 1,
      testItem: "马达减速测试",
      testReq: "温度调节控制在测试时不起作用",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-3",
      testNum: 1,
      testItem: "马达减速测试",
      testReq: "模仿马达+器具负载调整到110%额定功率，器具内马达调节电压达到额定电压下的转速，并记录下这个马达工作电压。如此持续运行30分钟",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-3",
      testNum: 1,
      testItem: "马达减速测试",
      testReq: "内部马达的电压按如下减少，记录每一步的马达转速：a) 马达操作电压30V或更小以每分钟1V的速度，或b) 其它所有马达以每分钟5V的速度",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-3",
      testNum: 1,
      testItem: "马达减速测试",
      testReq: "温控器动作断开电路时记录这个点的马达电压和转速。如果温控器不动作，马达速度减少到温度保险丝断开或停机状态",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-4",
      testNum: 1,
      testItem: "毛巾包裹测试",
      testReq: "额定电压（125V 60Hz），高热高速开机运行30分钟两层棉绒毛巾完全包裹住器具",
      judgeStandard: "没有发现着火、冒烟绝缘耐压测试（1250V 100mA 1分钟）没有失败测试后没有故障和异常",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-5",
      testNum: 1,
      testItem: "温控器跳开实验 1",
      testReq: "额定电压（125V 60Hz），设定高热高速设置",
      judgeStandard: "没有火星喷出、短路、断路的现象测试完成后出风口不应熔胶、变形现象",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "7.异常操作",
      No: "7-5",
      testNum: 1,
      testItem: "温控器跳开实验 1",
      testReq: "200mm×200mm×50 um的聚乙烯薄膜完全贴着进气口自然吸住",
      judgeStandard: "温控器3-10秒内跳开",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "7.异常操作",
      No: "7-5",
      testNum: 1,
      testItem: "温控器跳开实验 1",
      testReq: "云母板堵住出风口",
      judgeStandard: "温控器3-10秒内跳开",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "7.异常操作",
      No: "7-6",
      testNum: 1,
      testItem: "温控器跳开实验 2",
      testReq:
        "1.1倍额定电压（110V 60Hz），带小风嘴，设定高档桌面平铺2层棉绒毛巾，风筒出风口向毛巾平放，持续运行30分钟，测试期间温度控制器跳开（功率回到冷风档位或完全断",
      judgeStandard: "没有火星喷出、短路、断路的现象测试完成后出风口不应熔胶、变形现象",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-7",
      testNum: 1,
      testItem: "覆盖试验",
      testReq: "UL 859：46.2项输入电压：额定电压(125V)设定档位：高档",
      judgeStandard: "粗棉布应不能变色、灼热或燃烧",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-7",
      testNum: 1,
      testItem: "覆盖试验",
      testReq: "不带附件，放置在软木板表面操作直到所有的温度稳定，然后松散的覆盖两层粗棉布。",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-7",
      testNum: 1,
      testItem: "覆盖试验",
      testReq: "粗棉布以打褶方式阻碍吹风机的气流和覆盖住最热的区域，但不要故意操纵导致过度限制气流",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-7",
      testNum: 1,
      testItem: "覆盖试验",
      testReq: "操作8小时或直到稳定条件建立为止，取决于哪个时间更长",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-8",
      testNum: 1,
      testItem: "锁马达测试",
      testReq: "UL 859：46.3项输入电压：额定电压(125V)设定档位：高档注：软件有过流保护的需要取消保护设置",
      judgeStandard: "马达绕组温度＜150℃没有引起任何材料着火或喷火、火花、熔融金属或类似的结果绝缘耐压1250V 100mA 1分钟测试合格",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-8",
      testNum: 1,
      testItem: "锁马达测试",
      testReq: "覆盖试验后样品用于此测试",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-8",
      testNum: 1,
      testItem: "锁马达测试",
      testReq:
        "锁定转子及单层粗棉布松散的覆盖器具。然后操作7.5小时或直到明显的稳定条件建立，取决于哪个时间更长。注：手持式吹风机是以排气口喷嘴向下45°角安装进行测试",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-9",
      testNum: 1,
      testItem: "发热元件打断试验（手持电吹风）",
      testReq: "UL 859：46.4.5项CSA 22.2 No.36：5.10.4项额定电压以最大热设定持续操作1小时任何一点发热线被切断，模拟使用旋转和移动",
      judgeStandard: "电气间隔不应减小至规定的限制探针不能接触发热导线",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-10",
      testNum: 1,
      testItem: "暴露于潮湿环境测试安装发刷和柔风器",
      testReq: "UL 859：47项样机在未通电的条件下经受测试配有多个配件装置，每个配件进行完整的潮湿测试",
      judgeStandard: "1250V 100mA 1分钟没有击穿",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-10",
      testNum: 1,
      testItem: "暴露于潮湿环境测试安装发刷和柔风器",
      testReq:
        "毛刷的梳齿或中心排刷垂直向下插入标准测试溶液，保持2秒钟。然后垂直从水中移出来，继而让配件底座朝上向垂直位置倾斜，保持5 秒钟。然后再垂直浸入水中。以每分钟6次的速率不间断地重复此操作10次",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-10",
      testNum: 1,
      testItem: "暴露于潮湿环境测试安装发刷和柔风器",
      testReq: "浸入周期结束后，仍保持在垂直位置，样机被完全密封包裹在金属箔里，有关部件(如开关和类似的)被置于最不利的位置，在不通电条件下经受绝缘耐电压测试",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-10",
      testNum: 1,
      testItem: "暴露于潮湿环境测试安装发刷和柔风器",
      testReq: "插入溶液的深度为使梳齿或鬃毛的外露底座在水面上",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-10",
      testNum: 1,
      testItem: "暴露于潮湿环境测试安装发刷和柔风器",
      testReq: "当保持在位置时，没有轴向转动，猛拉或摇动，以降低样机浸入测试溶液",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "7.异常操作",
      No: "7-10",
      testNum: 1,
      testItem: "暴露于潮湿环境测试安装发刷和柔风器",
      testReq: "标准测试溶液：每升水含1/2 克硫化钙",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const isolatePerformanceList = ref([
    {
      distinguish: "8.绝缘性能",
      No: "8-1",
      testNum: 3,
      testItem: "绝缘耐压测试(UL)",
      testReq: "AC 1250V实验时间1分钟出风口、电路板周围装配间隙、外露紧固螺丝、旋转连接器周围用铝箔覆盖",
      judgeStandard: "漏电流：不超过100mA",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "8.绝缘性能",
      No: "8-1",
      testNum: 3,
      testItem: "绝缘耐压测试(UL)",
      testReq: "室温条件",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "8.绝缘性能",
      No: "8-1",
      testNum: 3,
      testItem: "UL 859：45125V加热至热稳态后立即进行",
      testReq: "室温条件",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: true,
      pr2: false,
      pp: true
    },
    {
      distinguish: "8.绝缘性能",
      No: "8-3",
      testNum: 3,
      testItem: "泄露电流(UL)",
      testReq: "额定电压125V，1分钟。发热板、电路板周围装配间隙、外露紧固螺丝、旋转连接器周围用铝箔覆盖",
      judgeStandard: "不超过0.5mA",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "8.绝缘性能",
      No: "8-3",
      testNum: 3,
      testItem: "泄露电流(UL)",
      testReq: "室温条件",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "8.绝缘性能",
      No: "8-3",
      testNum: 3,
      testItem: "泄露电流(UL)",
      testReq: "UL 859：38.6项，热稳态额定电压（125V）加热至热稳态后立即进行",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "8.绝缘性能",
      No: "8-3",
      testNum: 3,
      testItem: "泄露电流(UL)",
      testReq: "UL 859：39项，潮湿态试样预热到刚好在34℃，在湿度88±2%，温度32±2℃放置48小时后立即通电进行测试",
      judgeStandard: "",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const safetyList = ref([
    {
      distinguish: "9.安全性",
      No: "9-1",
      testNum: 1,
      testItem: "爬电距离",
      testReq: "UL 859：26.1带电部件到手可触摸部件及外露金属部件极性相反的部件间",
      judgeStandard: "功能绝缘：1.6mm以上（电源输入端）基本绝缘：1.6mm以上",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "9.安全性",
      No: "9-1",
      testNum: 1,
      testItem: "针对开关电源产品",
      testReq: "UL 859：26.2PCB上的绝缘要求",
      judgeStandard: "依据UL 840判定",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "9.安全性",
      No: "9-1",
      testNum: 1,
      testItem: "",
      testReq: "CSA 22.2 NO.36：5.2.4项",
      judgeStandard: "外壳的任何部分距离加热元件大于10毫米，或外壳材料为5VA等级",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "9.安全性",
      No: "9-2",
      testNum: 1,
      testItem: "电气间隔",
      testReq: "UL 859：26.1带电部件到手可触摸部件及外露金属部件极性相反的部件间",
      judgeStandard: "功能绝缘：1.6mm以上（电源输入端）基本绝缘：1.6mm以上",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "9.安全性",
      No: "9-2",
      testNum: 1,
      testItem: "针对开关电源产品",
      testReq: "UL 859：26.2PCB上的绝缘要求",
      judgeStandard: "依据UL 840判定",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "9.安全性",
      No: "9-3",
      testNum: 1,
      testItem: "绝缘物的厚度",
      testReq: "UL 859：26.1.7",
      judgeStandard: "基本绝缘：0.8mm功能绝缘：0.8mm",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "9.安全性",
      No: "9-4",
      testNum: 3,
      testItem: "旋转组件安全测试",
      testReq: "UL 859：51项样品在旋转组件正常温度测试时高10℃（18℉）环境下保持7小后立即通电在额定功率的时候测试。环境温度最小70℃（158℉）。",
      judgeStandard: "线没有位移电气电路没有间断接触软线没有损害能经受1250V 100mA 1min绝缘耐压测试",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "9.安全性",
      No: "9-5",
      testNum: 1,
      testItem: "实验指评估",
      testReq: "UL 859：8.5.3项UL 859图8.1试验指在结构的各开口施加1N的力",
      judgeStandard: "关节在各个方向不能接触带电体",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "9.安全性",
      No: "9-5",
      testNum: 1,
      testItem: "实验指评估",
      testReq: "UL 859：13.3.1.18项UL 859图13.3试验指在结构的各开口",
      judgeStandard: "不能接触带电体",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const dependenceList = ref([
    {
      distinguish: "10.可靠性",
      No: "10-1",
      testNum: 1,
      testItem: "温控器工作温度",
      testReq: "输入电源：125V 60Hz（设定档位开机后的电压）设定档位：高档出风口不带风嘴和带最小风口的风嘴出风口向上45°、向下45°、水平对墙25.4mm，所有方向运行",
      judgeStandard: "运行时和关机后的最高温度小于额定断开温度",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "10.可靠性",
      No: "10-2",
      testNum: 1,
      testItem: "温度保险丝工作温度",
      testReq: "输入电源：125V 60Hz（设定档位开机后的电压）设定档位：高档出风口不带风嘴和带最小风口的风嘴出风口向上45°、向下45°、水平对墙25.4mm，所有方向运行",
      judgeStandard: "运行时和关机后的最高温度小于Th值-20℃",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "10.可靠性",
      No: "10-3",
      testNum: 1,
      testItem: "塑胶应力测试（对于PC料）",
      testReq: "室温条件下将风叶置于乙酸乙酯和甲醇的1:3混合液体内15分钟，测试完成后立即用清水冲净晾干检查施加部件：风叶、前端盖、按键盖、推钮、尾套",
      judgeStandard: "不能有爆裂、裂纹",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "10.可靠性",
      No: "10-4",
      testNum: "各1个",
      testItem: "电路元件故障",
      testReq: "UL 859：46.6输入电源：125V 60Hz设定档位：高档短路和开路电路中的电子元件，每次只施加一个故障",
      judgeStandard: "没有喷射出火焰（1秒以下）、熔融金属、产生1根烟产生的二手烟烟量或可点燃的气体，和粗棉布和白薄纸没有着火迹象（如焦黑态）绝缘耐压测试合格",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const envExperimentList = ref([
    {
      distinguish: "11.环境实验",
      No: "11-1",
      testNum: 2,
      testItem: "低温使用环境试验",
      testReq: "0℃放置2小时后，仍在0℃环境进行试验",
      judgeStandard: "开关操作顺畅，无卡顿操作指示明亮、显示清晰、无缺损",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-1",
      testNum: 2,
      testItem: "低温使用环境试验",
      testReq: "功率：125V 60Hz",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）中档：？？？W低档：？？？W冷风+高档：？？？W冷风+中档：？？？W冷风+低档：？？？W",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-1",
      testNum: 2,
      testItem: "低温使用环境试验",
      testReq: "转速：125V 60Hz",
      judgeStandard: "高档：？？？r.p.m中档：？？？r.p.m低档：？？？r.p.m冷风+高档：？？？r.p.m冷风+中档：？？？r.p.m冷风+低档：？？？r.p.m",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-2",
      testNum: 2,
      testItem: "高温使用环境试验",
      testReq: "40℃放置2小时后，仍在40℃环境进行试验",
      judgeStandard: "开关操作顺畅，无卡顿操作指示明亮、显示清晰、无缺损",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-2",
      testNum: 2,
      testItem: "高温使用环境试验",
      testReq: "功率：125V 60Hz",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）中档：？？？W低档：？？？W冷风+高档：？？？W冷风+中档：？？？W冷风+低档：？？？W",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-2",
      testNum: 2,
      testItem: "高温使用环境试验",
      testReq: "转速：125V 60Hz",
      judgeStandard: "高档：？？？r.p.m中档：？？？r.p.m低档：？？？r.p.m冷风+高档：？？？r.p.m冷风+中档：？？？r.p.m冷风+低档：？？？r.p.m",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-3",
      testNum: 2,
      testItem: "低温存储",
      testReq: "温度-20℃放置48小时后，在室温环境进行试验",
      judgeStandard: "结构配合良好，没有变形、异响喷漆、色调不良金属部生锈等开关操作操作顺畅，无卡顿操作指示明亮、显示清晰、无缺损",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-3",
      testNum: 2,
      testItem: "低温存储",
      testReq: "功率：125V 60Hz",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-3",
      testNum: 2,
      testItem: "低温存储",
      testReq: "转速：125V 60Hz",
      judgeStandard: "冷风+高档：？？？r.p.m",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-4",
      testNum: 2,
      testItem: "高温高湿存储",
      testReq: "温度70℃湿度95%放置48小时后，在室温环境进行试验",
      judgeStandard: "结构配合良好，没有变形、异响喷漆、色调不良金属部生锈等开关操作操作顺畅，无卡顿操作指示明亮、显示清晰、无缺损",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-4",
      testNum: 2,
      testItem: "高温高湿存储",
      testReq: "功率：125V 60Hz",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-4",
      testNum: 2,
      testItem: "高温高湿存储",
      testReq: "转速：125V 60Hz",
      judgeStandard: "冷风+高档：？？？r.p.m",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-5",
      testNum: 2,
      testItem: "冷热冲击实验",
      testReq: "-20℃⇔85℃各1h，共10周期（5分钟内温变）试验后，在室温环境测试",
      judgeStandard: "结构配合良好，没有变形喷漆、色调不良金属部生锈等开关操作操作顺畅，无卡顿操作指示明亮、显示清晰、无缺损",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-5",
      testNum: 2,
      testItem: "冷热冲击实验",
      testReq: "功率：125V 60Hz",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-5",
      testNum: 2,
      testItem: "冷热冲击实验",
      testReq: "转速：125V 60Hz",
      judgeStandard: "冷风+高档：？？？r.p.m",
      judgeResult: "参考",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-6",
      testNum: 2,
      testItem: "耐光性（本体）",
      testReq: "放射照度：500W/m³照射时间：10小时温度：63℃",
      judgeStandard: "没有变色",
      judgeResult: "必须",
      dr1: false,
      t1: true,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "11.环境实验",
      No: "11-7",
      testNum: 2,
      testItem: "耐光性（彩盒）",
      testReq: "放射照度：500W/m³照射时间：10小时温度：63℃",
      judgeStandard: "没有变色",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "11.环境实验",
      No: "11-8",
      testNum: "各2个",
      testItem: "颜色转移",
      testReq: "70℃放置24h",
      judgeStandard: "电源线、涂装、印刷部、PE袋等有无转移",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "11.环境实验",
      No: "11-8",
      testNum: "各2个",
      testItem: "颜色转移",
      testReq: "本体缠绕电源线",
      judgeStandard: "电源线、涂装、印刷部、PE袋等有无转移",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "11.环境实验",
      No: "11-8",
      testNum: "各2个",
      testItem: "颜色转移",
      testReq: "完整包装样品",
      judgeStandard: "电源线、涂装、印刷部、PE袋等有无转移",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "11.环境实验",
      No: "11-9",
      testNum: "各2个",
      testItem: "人工汗液测试",
      testReq: "→ 涂抹酸液，酸性PH值：PH4.7→ 涂抹碱液，碱性PH值：PH8.8→ 存储环境：55℃，48H",
      judgeStandard: "产品外观面不允许有生锈、腐蚀、变色等异常现象",
      judgeResult: "参考",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "11.环境实验",
      No: "11-10",
      testNum: 2,
      testItem: "盐雾试验",
      testReq: "5%的氯化钠盐水溶液，溶液PH值调中性范围（6.5～7.2）喷雾量：1-2mL/80cm2时间：喷雾12h实验温度：+35℃士2℃",
      judgeStandard: "总腐蚀面积＜3%，和直径大于1mm/dm2锈点不多于2 个；试样表面小于1dm2不允许出现锈点；外观无异常；电气性能正常。",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "11.环境实验",
      No: "11-11",
      testNum: "各1套",
      testItem: "耐药品性",
      testReq: "125V 60Hz，设置在最高热量档位每次通电15分钟后喷涂药剂，1回/天，共测试10天（参照右侧作业指引）",
      judgeStandard: "",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "11.环境实验",
      No: "11-11",
      testNum: "各1套",
      testItem: "耐药品性",
      testReq:
        "不同样品使用下述药品涂抹与发热板和外壳上分别进行验证直接烫发用油（欧莱德香槟玫瑰油）直发保湿喷雾（施华蔻金致润养精油营养水）摩丝（沙宣强力持久造型摩丝）发泥（沙宣逆重哑光发泥）直发保持精华液（力士臻采护发油珠精华凝雾）",
      judgeStandard: "无裂痕、裂纹、变色（试剂会造成外观变化的除外）现象",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    }
  ]);

  const machineFullList = ref([
    {
      distinguish: "12.整机耐久性",
      No: "12-1",
      testNum: 5,
      testItem: "整机寿命测试",
      testReq: "输入电源：125V 60Hz设定档位：高档15分钟开，15分钟关，开状态1000小时",
      judgeStandard: "膜层没有松脱、起皮、鼓包外表面没有变色没有内部构造的破损和带电部件外露电气连接触点没有打火痕迹绝缘耐压符合规格要求",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "12.整机耐久性",
      No: "12-1",
      testNum: 5,
      testItem: "整机寿命测试",
      testReq: "额定功率：125V 60Hz",
      judgeStandard: "变化小于初值±10%",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "12.整机耐久性",
      No: "12-1",
      testNum: 5,
      testItem: "整机寿命测试",
      testReq: "转速：125V 60Hz",
      judgeStandard: "变化小于初值±10%",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "12.整机耐久性",
      No: "12-1",
      testNum: 5,
      testItem: "整机寿命测试",
      testReq: "风速：125V 60Hz",
      judgeStandard: "变化小于初值±10%",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const partDurabilityList = ref([
    {
      distinguish: "13.部品耐久性",
      No: "13-1",
      testNum: 2,
      testItem: "涂层耐磨测试（头发作用非金属面）",
      testReq:
        "输入额定电压125V 60Hz，设定在高档模拟使用卷发和拉直发，速率约6-12次/分钟，共测试1000次（注：头发每次都要经过同一个位置）每拉10次（此数字仅做参考）喷一次负离子护发素在头发上",
      judgeStandard: "涂层无漏底、脱落、起皮现象褪色商定标准",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-2",
      testNum: 2,
      testItem: "丝印或喷油涂层摩擦试验",
      testReq:
        "120℃（材料耐温低于120℃，用材料最高耐温值）环境静置30分钟，拿出后立即进行测试。500g力，12次/分钟擦拭50周次注：砝码头上包棉布（内部可垫棉花），接触面积为1cm2",
      judgeStandard: "不能有披覆层脱落、露底和褪色现象",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-2",
      testNum: 2,
      testItem: "丝印或喷油涂层摩擦试验",
      testReq: "无水酒精（浓度≧95℅）",
      judgeStandard: "不能有披覆层脱落、露底和褪色现象",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-2",
      testNum: 2,
      testItem: "丝印或喷油涂层摩擦试验",
      testReq: "正己烷",
      judgeStandard: "不能有披覆层脱落、露底和褪色现象",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-3",
      testNum: 2,
      testItem: "喷镀层硬度试验",
      testReq:
        "笔头磨平的三菱（Hi-uni）铅笔，9.8N力量，以45°角0.5mm/秒的速率划3mm以上。划拉5次，每次在不同位置。认定有2次以上划痕时，用下1阶段的铅笔进行试验。",
      judgeStandard: "划痕不足2次时的铅笔硬度作为喷镀层硬度",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-3",
      testNum: 2,
      testItem: "喷镀层硬度试验",
      testReq: "非金属面喷镀层",
      judgeStandard: "≥2H",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-3",
      testNum: 2,
      testItem: "喷镀层硬度试验",
      testReq: "金属面喷镀层",
      judgeStandard: "≥4H",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-4",
      testNum: "",
      testItem: "喷镀层及丝印热骤降试验",
      testReq: "白格刀划100个1mm²的小方格，样品以功能测试或正常温升测试中的最高温度加热1小时，紧接着立即置于冷水中（水温低于30",
      judgeStandard: "无喷镀层崩裂、脱落3M胶粘符合要求",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-5",
      testNum: 2,
      testItem: "丝印或喷油涂层附着力试验",
      testReq: "白格刀划100个1mm²的小方格3M 600#透明胶纸紧贴方格表面，然后成45度角快速撕掉胶纸重复3次",
      judgeStandard: "喷镀层和丝印无掉落现象",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-6",
      testNum: 2,
      testItem: "档位开关寿命测试",
      testReq: "输入额定电压125V 60Hz，设定在高档12周次/分钟的速率操作10000周次",
      judgeStandard: "操作顺畅，没有卡顿；电性能没有异常操作力：变化小于初值±20%",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-7",
      testNum: 2,
      testItem: "冷风开关寿命测试",
      testReq: "输入额定电压125V 60Hz，设定在高档12周次/分钟的速率操作10000周次",
      judgeStandard: "操作顺畅，没有卡顿；电性能没有异常操作力：变化小于初值±20%",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-8",
      testNum: "各2个",
      testItem: "连接件拆装测试",
      testReq: "每个配件装入和拔出手柄5000次（可以通过尺寸测量，取最大配合间隙和最小配合间隙的配件样品）速率是10周次/分钟",
      judgeStandard: "操作顺滑，没有变形，没有异响操作力：变化小于初值±20%",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-9",
      testNum: 3,
      testItem: "旋转耐久性测试",
      testReq:
        "UL859：52.4项a 额定电流，10周次/分钟，负重1/4磅（113克）0°→ -100°→ 0°→ +100°→ 0°为一个周期，共测试100000周次b 两条引导杆之间空50.8mm，距软线入口轴心114mm",
      judgeStandard: "旋转连接器仍然能按预定功能操作软线或软线旋转连接器没有损坏没有未绝缘带电部件外露绝缘耐压测试合格",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-10",
      testNum: 3,
      testItem: "电源线缠绕实验",
      testReq: "转环固定，0.2-0.5A电流，0°→ 1080°→ 0°为一个周期将电源线缠绕在器具手柄上，负重500g，速率3周次/min，共6000周次。",
      judgeStandard: "铜芯没有全断没有短路软线无损伤绝缘耐压没有失败",
      judgeResult: "参考",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-11",
      testNum: 3,
      testItem: "电源线挠曲测试",
      testReq:
        "UL859：49.2项，转环固定a 试样在温度100℃(212℉)空气流通的烤箱内保持96小时，接着试样仍在烤箱内，调节及冷却烤箱室内的温度至23±2℃(73±3.6℉)，然后进行测试。b 额定电流，10周次/分钟，负重1/4磅（113克），0°→540°→ 0°为一个周期，c 共测试6000周次d 两条引导杆之间空50.8mm，距软线入口轴心114mm",
      judgeStandard: "软线或软线旋转连接器没有损坏没有未绝缘带电部件外露绝缘耐压测试合格",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-12",
      testNum: 3,
      testItem: "ALCI断路器电源线摇摆测试",
      testReq: "UL859：50项a 0.2-0.5A电流，10周次/分钟，负重1/4磅（113克），±90°为一个周期，共测试6000周次b 两条引导杆之间空19mm，距软线入口229mm",
      judgeStandard: "没有电流中断没有未绝缘带电部件外露绝缘耐压测试合格",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "13.部品耐久性",
      No: "13-13",
      testNum: 3,
      testItem: "电源线弯曲试验",
      testReq:
        "CSA 22.2 NO.36：7.12.2项电源软线可能弯折的最大角度（软线不超过手柄），正反两个方向为一周次，110g施加于软线距入口203mm处，10次/分钟，10000周次，50%额定电流",
      judgeStandard: "仍能正常通电导体没有从端子分离软线和护套松脱和损坏绝缘耐压没有失败",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const temperatureTestList = ref([
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "UL 859：44项输入电压：额定电压(125V)设定：高档",
      judgeStandard: "没有火险、熔融物",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "外壳（上，距出风口50mm）",
      judgeStandard: "＜50K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "外壳（下，距发热板50mm）",
      judgeStandard: "＜50K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "外壳（左，距出风口50mm）",
      judgeStandard: "＜50K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "外壳（右，距发热板50mm）",
      judgeStandard: "＜50K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "手柄",
      judgeStandard: "＜50K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "外壳（上，距出风口12.7mm）",
      judgeStandard: "＜70K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "外壳（下，距发热板12.7mm）",
      judgeStandard: "＜70K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "外壳（左，距出风口12.7mm）",
      judgeStandard: "＜70K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-1",
      testNum: 1,
      testItem:
        "正常温升测试UL 859：44项输入电压：额定电压(125V)设定：高档没有火险、熔融物 必须 √UL 859: 44.3热气卷发钳和梳子,一个扇形区域进气口打开，其它进气口全部堵住。以及堵住3/4出气气口。持续操作30分钟。",
      testReq: "外壳（右，距发热板12.7mm）",
      judgeStandard: "＜70K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "14.温升测试",
      No: "14-2",
      testNum: 1,
      testItem: "软木材表面温度测试",
      testReq: "UL 859：46.4.1项输入电压：额定电压(125V)设定档位：高档手持吹风机放置在水平且盖有两层白纸的软木材表面上，操作直至温度稳定",
      judgeStandard: "纸上的温升应不超过125K",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const destructionList = ref([
    {
      distinguish: "15.恶意破坏",
      No: "15-1",
      testNum: 2,
      testItem: "冷风按键键恶意操作",
      testReq: "两倍操作力间断按、瞬间按、快速按等，模拟在实际使用中可能遭遇的恶意操作情况",
      judgeStandard: "没有破坏没有误动作，功能正常",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "15.恶意破坏",
      No: "15-2",
      testNum: "",
      testItem: "锁键恶意操作",
      testReq: "两倍操作力操作打开和关闭锁键",
      judgeStandard: "没有破坏",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    },
    {
      distinguish: "15.恶意破坏",
      No: "15-3",
      testNum: 2,
      testItem: "静压力测试",
      testReq: "整机任何方向，其上方放置一块200*200*20mm的软木板，软木上方施加660N×1分钟的静压力",
      judgeStandard: "没有破坏没有带电部件露出、外观异常、操作异常、外壳断裂等异常现象，绝缘耐压测试合格",
      judgeResult: "必须",
      dr1: true,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: false
    }
  ]);

  const transportList = ref([
    {
      distinguish: "16.运输",
      No: "16-1",
      testNum: 2,
      testItem: "个装跌落",
      testReq: "高度：80cm/150cm测试点①最弱1角②最弱3稜③面(6面)跌落面：水泥面或类似表面",
      judgeStandard:
        "80cm跌落：产品外观、结构及操作无异常；基本性能满足要求；绝缘性能正常150cm跌落：没有有害破损，绝缘性能正常※ 落下导致外观表面的凹陷，伤，为允许。但是不能对皮肤有影响，会影响销售的箱子破损",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-1",
      testNum: 2,
      testItem: "个装跌落",
      testReq: "功率：125V 60Hz",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-1",
      testNum: 2,
      testItem: "个装跌落",
      testReq: "转速：125V 60Hz",
      judgeStandard: "冷风+高档：？？？r.p.m",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-2",
      testNum: "",
      testItem: "震箱测试",
      testReq: "GB/T 4857.17；ISO 4180震动频率：5～55Hz震动速度：各方向0.92～1.25G震动方向：上下・左右・前后震动时间：垂直30分，水平2方向15分",
      judgeStandard: "螺丝等装配部分有没有松动、开裂，内部引线是否有损伤等",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-2",
      testNum: "",
      testItem: "震箱测试",
      testReq: "功率：125V 60Hz",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-2",
      testNum: "",
      testItem: "震箱测试",
      testReq: "转速：125V 60Hz",
      judgeStandard: "冷风+高档：？？？r.p.m",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-3",
      testNum: "",
      testItem: "包装压缩试验",
      testReq:
        "GB/T 4857.17；ISO 4180完整的包装试样置于压板的中心位置堆码时最底层包装所承受重量，施加压力持续24小时压缩重量？？Kg（2.72米÷包装放置高度，取整×包装毛重）长方体考虑3面",
      judgeStandard: "产品无变形、破损包装箱无弯曲、鼓起、凹陷",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-4",
      testNum: "",
      testItem: "摔箱测试",
      testReq:
        "GB/T 4857.17；ISO 4180高度：？？Cm（重量≤10kg，80cm；10kg＜重量≤20kg，60cm；20kg＜重量≤30kg，45cm）测试点①最弱1角②最弱3稜③面(6面)跌落面：水泥面或类似表面",
      judgeStandard:
        "商品（本体・彩盒・辅材等所有部件）外观、结构及操作无异常；基本性能满足要求；个装箱无明显破损（角、棱落下附近的彩盒变形允许）产品不能从内托脱出※ 外箱能够保护产品，落下后产品无损伤",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-4",
      testNum: "",
      testItem: "摔箱测试",
      testReq: "功率：125V 60Hz",
      judgeStandard: "高档：630-735W（额定值：700W +5%/-10%）",
      judgeResult: "必须",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    },
    {
      distinguish: "16.运输",
      No: "16-4",
      testNum: "",
      testItem: "摔箱测试",
      testReq: "转速：125V 60Hz",
      judgeStandard: "冷风+高档：？？？r.p.m",
      judgeResult: "参考",
      dr1: false,
      t1: false,
      t2: false,
      pr1: false,
      pr2: false,
      pp: true
    }
  ]);

  return {
    transportList,
    appearanceList,
    temperatureTestList,
    partDurabilityList,
    machineFullList,
    envExperimentList,
    dependenceList,
    isolatePerformanceList,
    machineList,
    safetyList,
    badOperationList,
    electPerformanceList,
    operationList,
    basePerformanceList,
    signList
  };
};
