import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftBold,
  ArrowRight,
  ArrowRightBold,
  ArrowUp,
  Back,
  Bottom,
  Box,
  Calendar,
  ChatRound,
  CircleClose,
  CirclePlus,
  Clock,
  Close,
  CloseBold,
  CollectionTag,
  Connection,
  CopyDocument,
  DArrowLeft,
  DArrowRight,
  DCaret,
  Delete,
  Document,
  DocumentChecked,
  DocumentCopy,
  DocumentDelete,
  Download,
  Edit,
  EditPen,
  Expand,
  Files,
  Filter,
  Fold,
  Folder,
  FolderOpened,
  Hide,
  Link,
  Loading,
  Menu,
  Message,
  MessageBox,
  More,
  MoreFilled,
  Notification,
  Paperclip,
  Picture,
  Plus,
  Pointer,
  Position,
  PriceTag,
  Printer,
  QuestionFilled,
  Rank,
  Refresh,
  RefreshLeft,
  RefreshRight,
  Remove,
  Right,
  ScaleToOriginal,
  Search,
  Select,
  SemiSelect,
  SetUp,
  Setting,
  Share,
  Sort,
  Star,
  StarFilled,
  Switch,
  SwitchButton,
  TakeawayBox,
  Tickets,
  Top,
  Upload,
  UploadFilled,
  User,
  View,
  Warning,
  WindPower,
  ZoomIn,
  ZoomOut
} from "@element-plus/icons-vue";

/** 按钮上的图标 */
export const IconConf = {
  Plus: <Plus />,
  Edit: <Edit />,
  Delete: <Delete />,
  Search: <Search />,
  Upload: <Upload />,
  Download: <Download />,
  EditPen: <EditPen />,
  CirclePlus: <CirclePlus />,
  Printer: <Printer />,
  MessageBox: <MessageBox />,
  TakeawayBox: <TakeawayBox />,
  SetUp: <SetUp />,
  Tickets: <Tickets />,
  Setting: <Setting />,
  WindPower: <WindPower />,
  Picture: <Picture />,
  CopyDocument: <CopyDocument />,
  Link: <Link />,
  Loading: <Loading />,
  Star: <Star />,
  Position: <Position />,
  View: <View />,
  Hide: <Hide />,
  Refresh: <Refresh />,
  RefreshRight: <RefreshRight />,
  RefreshLeft: <RefreshLeft />,
  User: <User />,
  ArrowLeftBold: <ArrowLeftBold />,
  ArrowRightBold: <ArrowRightBold />,
  DArrowLeft: <DArrowLeft />,
  DArrowRight: <DArrowRight />,
  Warning: <Warning />,
  Close: <Close />,
  CloseBold: <CloseBold />,
  More: <More />,
  MoreFilled: <MoreFilled />,
  Message: <Message />,
  Document: <Document />,
  Calendar: <Calendar />,
  PriceTag: <PriceTag />,
  Paperclip: <Paperclip />,
  CollectionTag: <CollectionTag />,
  Files: <Files />,
  Folder: <Folder />,
  FolderOpened: <FolderOpened />,
  Box: <Box />,
  DocumentCopy: <DocumentCopy />,
  DCaret: <DCaret />,
  Rank: <Rank />,
  Fold: <Fold />,
  Expand: <Expand />,
  Filter: <Filter />,
  Notification: <Notification />,
  Connection: <Connection />,
  Clock: <Clock />,
  SwitchButton: <SwitchButton />,
  DocumentChecked: <DocumentChecked />,
  Sort: <Sort />,
  ZoomOut: <ZoomOut />,
  ZoomIn: <ZoomIn />,
  Menu: <Menu />,
  Share: <Share />,
  StarFilled: <StarFilled />,
  Select: <Select />,
  SemiSelect: <SemiSelect />,
  ChatRound: <ChatRound />,
  Top: <Top />,
  Right: <Right />,
  Bottom: <Bottom />,
  Back: <Back />,
  DocumentDelete: <DocumentDelete />,
  ScaleToOriginal: <ScaleToOriginal />,
  ArrowLeft: <ArrowLeft />,
  ArrowUp: <ArrowUp />,
  ArrowRight: <ArrowRight />,
  ArrowDown: <ArrowDown />,
  UploadFilled: <UploadFilled />,
  Switch: <Switch />,
  CircleClose: <CircleClose />,
  Pointer: <Pointer />,
  Remove: <Remove />
};

// 提示图标
export const Question = (props: { label?: string; tipMsg?: string | JSX.Element; Icon?: any; placement?: string; color?: string; size?: number }) => {
  const { label, tipMsg = "提示", Icon = QuestionFilled, placement = "top", color = "orange", size = 14 } = props;
  return (
    <span>
      {label ? <span>{label}</span> : null}
      <el-tooltip placement={placement} content={tipMsg}>
        {{
          default: () => (
            <el-icon style="margin: 1px 0 0 2px" class="ui-va-tt" size={size}>
              {<Icon color={color} />}
            </el-icon>
          ),
          content: () => tipMsg
        }}
      </el-tooltip>
    </span>
  );
};
